=== JuPedSim/JuPedSim/JPSreport/xsd/jps_report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="JPSreport">
    <xs:complexType>
      <xs:all>
        <xs:element name="geometry">
          <xs:annotation>
            <xs:documentation>geometry file</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="file" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="trajectories">
          <xs:annotation>
            <xs:documentation>trajectories file and format  either a file name or a path location. In the latter case all files in the directory will be used</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="file" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="name" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="path">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="location" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="format" use="required"/>
            <xs:attribute type="xs:string" name="unit" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="measurementAreas">
          <xs:annotation>
            <xs:documentation>all files in the directories will be used</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="area_B" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="vertex" maxOccurs="unbounded" minOccurs="4">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="x"  use="required"/>
                            <xs:attribute type="xs:float" name="y"  use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Length_in_movement_direction" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="distance" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="id" use="required"/>
                  <xs:attribute type="xs:string" name="type" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="area_L" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="start">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="x" use="required"/>
                            <xs:attribute type="xs:float" name="y" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="end">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="x" use="required"/>
                            <xs:attribute type="xs:float" name="y" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="id" use="required"/>
                  <xs:attribute type="xs:string" name="type" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="unit" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="velocity">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="useXComponent"/>
              <xs:element type="xs:string" name="useYComponent"/>
              <xs:element type="xs:int" name="halfFrameNumberToUse">
                <xs:annotation>
                  <xs:documentation>half of the time interval that used to calculate instantaneous velocity 
         of ped i [fr] here v_i = (X(t+deltaF) - X(t+deltaF))/(2*deltaF). X is location.</xs:documentation>
                </xs:annotation>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="method_A">
          <xs:annotation>
            <xs:documentation>Method A (Zhang2011a) Flow and Vel</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="timeInterval" >
                <xs:annotation>
                  <xs:documentation>Time interval used to count the flow [fr]</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:int" >
                      <xs:attribute type="xs:string" name="unit"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="measurementArea" maxOccurs="unbounded" minOccurs="1">
                <xs:annotation>
                  <xs:documentation>The coordinate of the line used to calculate the flow and velocity</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="enabled"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="method_B">
          <xs:annotation>
            <xs:documentation>Method B (Zhang2011a) Vel and Dens based on Tin and Tout</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="measurementArea" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="enabled"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="method_C">
          <xs:annotation>
            <xs:documentation>Method C (Zhang2011a) Classical density and Vel</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="measurementArea" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="enabled"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="method_D">
          <xs:annotation>
            <xs:documentation>Method D (Zhang2011a) Voronoi density and Vel</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="measurementArea" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="cutByCircle">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="enabled"   use="required"/>
                      <xs:attribute type="xs:double" name="radius"  use="required"/>
                      <xs:attribute type="xs:int" name="edges"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="getProfile">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="enabled"  use="required"/>
                      <xs:attribute type="xs:float" name="scale_x"  use="required"/>
                      <xs:attribute type="xs:float" name="scale_y"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="enabled"  use="required"/>
            <xs:attribute type="xs:string" name="outputGraph"  use="required"/>
            <xs:attribute type="xs:string" name="individualFDdata"  use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:all>
      <xs:attribute type="xs:string" name="project"  use="required"/>
      <xs:attribute name="version" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:float">
            <xs:enumeration value="0.6" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JuPedSim/JuPedSim/JPSreport/demos/bottleneck/input_AO_300.xml
<?xml version="1.0" encoding="UTF-8"?> 

<JPSreport project="JPS-Project" version="0.6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/0.6/jps_report.xsd" > 
    <!-- geometry file --> 
    <geometry file = "geo_AO_300.xml" /> 
    <!-- trajectories file and format --> 
    <!-- either a file name or a path location. In the latter case all files in the directory will be used--> 
    <trajectories format="txt" unit="m"> 
        <file name="AO_300.txt" /> 
        <path location="./" /> 
    </trajectories> 
    <!-- all files in the directories will be used --> 

    <measurementAreas unit="m"> 
        <area_B id="1" type="BoundingBox"> 
            <vertex x="2.40" y="0.53" /> 
            <vertex x="2.40" y="-0.53" /> 
            <vertex x="-0.60" y="-0.53" /> 
            <vertex x="-0.60" y="0.53" /> 
            <Length_in_movement_direction distance="1.06" /> 
        </area_B> 
        <area_L id="2" type="Line"> 
            <start x="-2.25" y="0.00" /> 
            <end x="4.00" y="0.00" /> 
        </area_L> 
    </measurementAreas> 

    <velocity> 
        <useXComponent>true</useXComponent> 
        <useYComponent>true</useYComponent> 
        <!-- half of the time interval that used to calculate instantaneous velocity of ped i [fr] here v_i = (X(t+deltaF) - X(t+deltaF))/(2*deltaF). X is location. --> 
        <halfFrameNumberToUse>5</halfFrameNumberToUse> 
    </velocity> 

    <!-- Method A (Zhang2011a) Flow and Vel --> 
    <method_A enabled="true"> 
        <!-- Time interval used to count the flow [fr] --> 
        <timeInterval unit="frame"> 
            16 
        </timeInterval> 
        <!-- The coordinate of the line used to calculate the flow and velocity --> 
        <measurementArea id="2" /> 
    </method_A> 

    <!-- Method B (Zhang2011a) Vel and Dens based on Tin and Tout --> 
    <method_B enabled="false"> 
        <measurementArea id="1" /> 
    </method_B> 

    <!-- Method C (Zhang2011a) Classical density and Vel --> 
    <method_C enabled="false"> 
        <measurementArea id="1" /> 
    </method_C> 

    <!-- Method D (Zhang2011a) Voronoi density and Vel --> 
    <method_D enabled="true" outputGraph="true" individualFDdata="false"> 
        <measurementArea id="1" /> 
        <cutByCircle enabled="true" radius= "1" edges = "10"/> 
        <!-- edges represent the precision of discretization of the circle --> 
        <getProfile enabled="false" scale_x="0.10" scale_y="0.10"/> 
    </method_D> 

</JPSreport>

=== JuPedSim/JuPedSim/JPSreport/demos/bottleneck/input_AO_240.xml
<?xml version="1.0" encoding="UTF-8"?>
<JPSreport project="JPS-Project" version="0.6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/0.6/jps_report.xsd" > 
    <!-- geometry file -->
    <geometry file = "geo_AO_240.xml" />
    <!-- trajectories file and format -->
    <!-- either a file name or a path location. In the latter case all files in the directory will be used-->
    <trajectories format="xml" unit="m">
        <file name="AO_240.xml" />
        <path location="./" />
    </trajectories>
    <!-- all files in the directories will be used -->

    <measurementAreas unit="m">
        <area_B id="1" type="BoundingBox">
            <vertex x="2.10" y="0.53" />
            <vertex x="2.10" y="-0.53" />
            <vertex x="-0.30" y="-0.53" />
            <vertex x="-0.30" y="0.53" />
			<Length_in_movement_direction distance="1.0"/>
        </area_B>
		<area_B id="2" type="BoundingBox">
            <vertex x="2.10" y="-0.53" />
            <vertex x="2.10" y="-1.53" />
            <vertex x="-0.30" y="-1.53" />
            <vertex x="-0.30" y="-0.53" />
        </area_B>
        <area_L id="3" type="Line">
            <start x="-2.25" y="0.00" />
            <end x="4.00" y="0.00" />
        </area_L>
		<area_L id="4" type="Line">
            <start x="-2.25" y="0.50" />
            <end x="4.00" y="0.50" />
        </area_L>
    </measurementAreas>

  <velocity>
    <useXComponent>true</useXComponent>
    <useYComponent>true</useYComponent>

    <!-- half of the time interval that used to calculate instantaneous velocity 
         of ped i [fr] here v_i = (X(t+deltaF) - X(t+deltaF))/(2*deltaF). X is location. -->
    <halfFrameNumberToUse>5</halfFrameNumberToUse>
  </velocity>

  <!-- Method A (Zhang2011a) Flow and Vel -->
  <method_A enabled="true">
    <!-- Time interval used to count the flow [fr] -->
    <timeInterval unit="frame">
      16
    </timeInterval>
    <!-- The coordinate of the line used to calculate the flow and velocity -->
    <measurementArea id="3" />
  </method_A>

  <!-- Method B (Zhang2011a) Vel and Dens based on Tin and Tout -->
  <method_B enabled="false">
    <measurementArea id="1" />
	<measurementArea id="2" />
  </method_B>

  <!-- Method C (Zhang2011a) Classical density and Vel -->
  <method_C enabled="false">
    <measurementArea id="1" />
	<measurementArea id="2" />
  </method_C>

  <!-- Method D (Zhang2011a) Voronoi density and Vel -->
  <method_D enabled="false" outputGraph="true" individualFDdata="false">
    <measurementArea id="1" />
	<measurementArea id="2" />
	<cutByCircle enabled="false" radius= "1" edges = "6"/>
    <getProfile enabled="false" scale_x="0.10" scale_y="0.10"/>
  </method_D>
</JPSreport>
